# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-01 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='CN', max_length=20),
        ),
    ]
